// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package database

import (
	"context"
)

const emptyChirps = `-- name: EmptyChirps :exec
TRUNCATE TABLE chirps RESTART IDENTITY CASCADE
`

func (q *Queries) EmptyChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, emptyChirps)
	return err
}

const emptyUsers = `-- name: EmptyUsers :exec
TRUNCATE TABLE users RESTART IDENTITY CASCADE
`

func (q *Queries) EmptyUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, emptyUsers)
	return err
}
